version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=user
      - POSTGRES_USER=alex
      - POSTGRES_DB=ai_finance

volumes:
  postgres-data:
    labels:
      com.docker.compose.project: ai_finance
      com.docker.compose.service: postgres
      purpose: database